export default {
  siteContainer: document.querySelector('.site-container'),
  dropdownBtn: document.querySelectorAll('.nav__dropdown'),
  dropdownMenu: document.querySelectorAll('.nav__down'),
  burgerBtn: document.querySelector('.burger'),
  burgerLine: document.querySelector('.burger__line'),
  burgerMenu: document.querySelector('.nav'),
  burgerMenuLink: document.querySelector('.nav__link'),
  header: document.querySelector('.header__container'),
  burgerClassesOpen: 'opened',
  burgerClassesOverflow: 'overflow',
  burgerClassesZIndex: 'z-index-1',
  burgerClassesWithoutBorder: 'without-border',
  burgerClassesBtnOpen: 'burger-open',
  burgerClassesLine: 'line-down',
  tabsBtn: document.querySelectorAll('.category-list__title'),
  tabsActiveClass: 'is-active',
}
